const DATA_NOT_FOUND = 'DATA_NOT_FOUND'
const LOADING = 'LOADING'
const LOADED_SUCCESS = 'LOADED_SUCCESS'

export default {
  DATA_NOT_FOUND: DATA_NOT_FOUND,
  LOADING: LOADING,
  LOADED_SUCCESS: LOADED_SUCCESS
}
